# PR 요청시 develop, release/*, hotfix/*에 요청하는 경우 테스트 코드 검사 실행
name: Pull Request Run Test

on:
  pull_request:
    branches:
      - 'develop'
      - 'release/*'
      - 'hotfix/*'

jobs:
  Unit_Test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Initialize
        run: |
          rm -rf build/
          rm -rfv ~/Library/Developer/Xcode/Archives/*

      - name: Tuist init
        run: tuist generate
        
      - name: Run Test Code
        run: sh ./script/run_test.sh
        
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult

      - name: Deinitialize
        run: rm -rf TestResults.xcresult
